CLASSIC_ROUTES_MODULES_USING = [
    ["withdraw_okx_sonic_eth"],
    ["bridge_relay_sonic"],
    ["process_sonic_series"],
    ["deposit_okx_sonic"],
]

PROCESS_WORMHOLE_BRIDGE = true
CONVER_FTM_AFTER_DEPOSIT = true